"""Centralized branding constants and helpers for all export outputs."""

import base64
import tempfile
import os

# ═══════════════════════════════════════════════════════════
# BRAND IDENTITY
# ═══════════════════════════════════════════════════════════

BRAND_NAME = "CRELYTIC"
COMPANY_NAME = "CRELYTIC"
PRODUCT_URL = "engine.crelytic.ai"
TAGLINE = "AI-Powered CRE Deal Underwriting"

# Standard text blocks
CONFIDENTIALITY = "Confidential — For intended recipient only. Not investment advice."
DISCLAIMER = (
    "Forward-looking projections are estimates only and subject to risks "
    "and uncertainties. Past performance is not indicative of future results."
)
GENERATED_BY = f"Generated by {BRAND_NAME} — {PRODUCT_URL}"

# ═══════════════════════════════════════════════════════════
# BRAND COLORS (hex, no #)
# ═══════════════════════════════════════════════════════════

COLOR_NAVY = "0A1628"
COLOR_NAVY_LIGHT = "0F2236"
COLOR_SURFACE = "132A42"
COLOR_BLUE = "3B82F6"
COLOR_TEAL = "00897B"
COLOR_GREEN = "166534"
COLOR_GREEN_BG = "DCFCE7"
COLOR_RED = "991B1B"
COLOR_RED_BG = "FEE2E2"
COLOR_AMBER_BG = "FEF3C7"
COLOR_LIGHT_BLUE = "EFF6FF"
COLOR_LIGHT_BLUE_BORDER = "DBEAFE"
COLOR_TEXT_PRIMARY = "E8EDF2"
COLOR_TEXT_SECONDARY = "8A9BB0"
COLOR_WHITE = "FFFFFF"

# ═══════════════════════════════════════════════════════════
# LOGO (Base64-encoded PNG, 180x180)
# ═══════════════════════════════════════════════════════════

LOGO_BASE64 = (
    "iVBORw0KGgoAAAANSUhEUgAAALQAAAC0CAYAAAA9zQYyAAAABmJLR0QA/wD/AP+gvaeTAAAK4klE"
    "QVR4nO3dbWxT1x3H8d85dmwnJDEQQkggCVDUAE5pgQQ2dQ+00rp23ZM0hY5uL6ZqarVu07Spqt"
    "QXmybtsZU6VVPVaVRTtUlVEbzqNnWimtp1q1rSkLQNMZC2WyAQhzzHIYljxz5nLxpQQp1g+97r"
    "ezn8PhIiJL7Hf+CbmxvH11fAYZs3HwilK2b2C6X3CIEmaNwKoAFAOYBVC7+TOaYXfs0A6IdGLwR"
    "6tRJdwfmJ9o8++ijp5J0LJxatb9pdJ33ykBbyS4D+NIBSJ+6HbjgJAG9p6Fekwkvnz3QO2n0Hd"
    "gYtG5v3fQ1aPayBLwDw2bg2mSejgVeh9OELZzr/CkDZsaj1oNvafA1nzh2CVk8AYqcNM9HNJyq0"
    "+M35yOYjOHYsY2UhS0E33LZnL5T8A4BWK+sQLXhPSPno+VPvvF3oAgUFXR2JlJei9GkA3wUgC7"
    "1zoiwUNA4n/anHhrq7Z/LdOO+gG5v37NCQR6HRnO+2RHnoVUIdvNjT1Z3PRnntXesjLYe0lp2M"
    "mYqgSWr5dn1z6wP5bJTzIxGNkZYfAHgeQCDfyYgKVCKAb6yurp2OjwzmdFydU9ANzS0/B/AkHH"
    "rcmmgFAkLcE66uQ3wk9sb1bnzdoOsjrY8K4Cl7ZiMqkMCB8Pq6eHwkdmKlm60YdGNk74P4+DCDe"
    "2bygnvC1RvPxkdi0eVusGyo9TtamoVEO4AyR0YjKsycD/JTfdF33s/2wayPctTs2rVKSBwFYybvC"
    "Smoo01Nd1Zk+2DWoIOZwO8A7HB0LKICaeDWOX/qyWwf+8QhR32ktVVAnwB/AkjepqRSd54707Xk"
    "m8Sl0ba1+QT04U+8n8h7pJK+Z9HWtuSBjSV/aJBl3wbwvaKORVS4usqRyTNTI7GeK+9YvCcWAB"
    "4v/kxEhRPQP8Wijq++0di87+t8jgbdeMTO+p0tX7nyp6tBa60fcWcgImuExMNX3wY+PgdQ+H394"
    "GlTdGNKS4j6c9GOS34AkD55SDPmm87GdaWINIZRFir+f318Zh6n+uIYjdtyErhfQX8TwDN+AFg4"
    "O9uOhekGUFlWgke+vBX7tle5OofSwGtdQ3jheB9SaavnyIp7ATwjtm3bFkwFV0+ALzVwUygL+vC"
    "rh3ZhU7V3/rt7+uL45YunkVGWdqqzgeTkWpkOrebrZtxEHry70VMxA0DzljDu21drdZmyZKByn8x"
    "o7LZjKPK+Er/E52+vdnuMrL7YusHyGkKK3VIINNkwD90ANq0rRSjgze/9N6wJoSxobTah0SS1Z"
    "tA3i9Kg3+0RVrSq1Np8GqJJCuiNNs1D5CoB1EtAVLo9CJEdNFAhwZezJXNUSPA0KzLHKgme0U3m"
    "EDwzhYzCoMkoDJqMwqDJKAyajMKgySgMmozCoMkoDJqMwqDJKAyajMKgySgMmozCoMkoDJqMwqDJ"
    "KAyajMKgySgMmozCoMkoDJqMwqDJKAyajMKgySgMmozCoMkoDJqMwqDJKAyajMKgySgMmozCoMko"
    "DJqMwqDJKAyajMKgySgMmozCoMko3r6aucdIKbHl9l1o3LkD5WvCkL7i/vOlkymMxgbw4ckujMUG"
    "i3rfNwoGnaPS inHg0AOoqqt1dY7VG9Zj2+470POfN/Hea2+4OosX8ZAjB1JKT8R8lRBo/txn0bS/"
    "1e1JPIdB52DL7bu8E/Midtx9ACXBoNtjeAqDzkHjju1uj5BVSTCImlu2uj2GpzDoHJRXrXF7hGVV"
    "rF3r9giewqBz4Cvyoxn58Pl9bo/gKQyajMKgySgMmozCoMkoDJqMwqDJKAyajMKgySgMmozCoMko"
    "DJqMwqDJKAyajMKgySgMmozCoMkoDJqMwqDJKAyajMKgySgMmozCoMkoDJqMwqDJKAyajMKgySgM"
    "mozBoMgqDJqMwaDIKgyajFOeVvIVAKFSKQCAIyCJ/DmmNdDqNudlpKKWKe99UdI4HHQiGUFWzAYFA"
    "yOm7WpFWChPjI7g8OeHqHOQsR4MOBEOo2dgAWey9chZCSqxdVwOfz4fJsVG3xyGHOFeaEKiq2eCJ"
    "mBcLr1mHQNDdrxbkHMdqC4VCrh9mLKci7N2rWpE1jgUdCJY6tbRlAV6s0liOBS08dqixmJS8FJqp"
    "nAvaqYWJVuDd3ShRARg0GYVBk1EYNBmFQZNRGDQZhUGTURg0GYVBk1EYNBmFQZNRGDQZhUGTURg0"
    "GYVBk1EYNBmFQZNRGDQZhUGTURg0GYVBk1EYNBmFQZNRGDQZhUGTURg0GYVBk1EkAO32EEQ20RLA"
    "rNtTENlkRgKYdnsKIptcloCecnsKIjsI4LLUEANOLM4Dcyo2DVyQQqDXkcVVxollbaHynC01N+fQJ"
    "NalErnPNptMOziJddMJa/MJ6F6ptTNBJ5NJJ5a1RTLPQMdiMYcmsW50IPcvsAOjCcwlvbmjuTSe"
    "QMLibFqgV2opumyaaYnkXALzXoxaa0xPTea1yQcdXYD23kHUeGwQYwO5f7LNpxVef3/YwYkK94+O"
    "S5bX0Eq/K0OJiRMAEtZHunZ1jZHhmOcuRxyfGEMqmd8eenxwEKf+/aZDExUmnUzh7Zf/Dp3nJ9p"
    "Lr/fjwrC3Hqk91RfHcetBzwZTU+/4xsfHM+H1dXcB2GrDbEuoTAaJ2WmEQmXw+YtzWfFlZ1EKE6"
    "PDmJocL2j7oXPnkUwksL6h3vW/y3hsEP86cgwTQ0N5b5vOaLx1ehQb1oSwqbrMgelypzTwauclP"
    "Pvyh0hnrH4FFK/19fb8WQBAfWTvTwTE0zbMuMx9CQSDIQSDIUi/v6hXyFJKYX4+hcTsDLQNXy1K"
    "gkHU3rIVlVVrUVLE6x1qrTE3PYPRgQGMDcTy3jNnU1cVQmRzGGsrAvD7ivcsiPm0wkh8Dt3/i2"
    "NsKmXPokL/qL+n8/cCALY076/J6MxFFOFi9kQOSPuEb1NfT/uQBIC+nvYhAfzT7amICnS8r6d9"
    "CFj0bDul9B/dm4eocBo4fOXtxYezoqG5pRsazS7MRFSoaH/05C4AClj6fGgtlPitOzMRFUYL8Qs"
    "sxAxc8wT/85HNRyDgyA9aiBzQcaGn49jidyx9rObYsYyGfASLiifyKKW0/iGuadV37a2mhgdi4eq"
    "6Wgi0FG00ojxp4LmLpzufv/b9WR9NT/pTjwH6tPNjERUkmgnpx7N9IGvQQ93dM9DyIHh6FnnPDO"
    "A7GOvszNrmsj/v7D/dEdVCPAQeT5N3KADf6Y+2L3v08Ilj6MWmhmPRypraEQFxv+2jEeVLiB/3R"
    "0++sNJNVgwaAKaGB0+G12/UAO6ybTCiPAnon/VHTz51vdtdN2gAiI/E3li9vm4UwL1AUZ8sR6Q19"
    "GP90c4nc7lxTkEDQHwk1hGu3ngWAvcDKCl4PKLczQD41oVo559y3SDvve3m2/ZuV0ocBXBbvtsS5"
    "eGskvrgxVOdp/LZKOc99BWTw4Ojodp1fynR/jUA9oKHIGQvpYHnMiHdNvBeZ94vsWEpxsYde/dA"
    "iuc0sN/KOkQAAIEumVHfP3em60ThS1gn6yMtDwjgCfAwhAoggG4lxK8Xnmhk6ecedh4uiPqdLV8"
    "VEg9D4x7wdC5aWRrAcQ0cvhA9+TfY9GJbjhz/LpyjeAjAfQA+A8Dd04vJK2YA8SaEeqVEzh/5b"
    "3e37S8S4vg3dJFIJDClg/uFFLuFlts19K2AbgBEOYByABVOz0BFdRnANKCnAdEvID7QQp3VSr9bK"
    "ZLt0WjUptO8s/s/vkLdIFEojCcAAAAASUVORK5CYII="
)


def get_logo_bytes() -> bytes:
    """Return the decoded PNG logo as bytes."""
    return base64.b64decode(LOGO_BASE64)


def get_logo_tempfile() -> str:
    """Write logo to a temp file and return the path. Caller should clean up."""
    logo_bytes = get_logo_bytes()
    tmp = tempfile.NamedTemporaryFile(suffix=".png", delete=False)
    tmp.write(logo_bytes)
    tmp.close()
    return tmp.name


def get_logo_base64_data_uri() -> str:
    """Return the logo as a data URI for HTML embedding."""
    return f"data:image/png;base64,{LOGO_BASE64}"


def cleanup_logo_tempfile(path: str):
    """Remove a temp logo file."""
    try:
        os.unlink(path)
    except OSError:
        pass
